server:
  port: 7000
spring:
  application:
    name: admin-server
eureka:
  client:
    service-url: #配置暴露给eureka Server的请求地址
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
