
server:
  port: 8002
spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.147.205:3306/sxt?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&rewriteBatchedStatements=true&useSSL=false
    username: root
    password: weinuo11
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0
  zipkin:
#    base-url: http://localhost:9411
    base-url: http://47.94.147.205:9411
  redis:
    database: 0
    host: 47.94.147.205
    port: 6379
    password: weinuo11
    timeout: 30
  session:
    store-type: redis

eureka:
  client:
    service-url: #配置暴露给eureka Server的请求地址
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
    #/Users/sxt/Desktop/sxt/moerlong/log/stdout.log

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:dao/*.xml
  type-aliases-package: com.sxt.dao
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false


